### ISSUE TITLE
Pressing x while typing makes tab closing

### ISSUE THREAD

**Issue by Sandmonster** [joseriosneto/qupzilla-vimplugin#14]
If you for example open google and try to search 'linux' your tab will be closed when you press x, so this makes browser useless.

**Comment by joseriosneto** [comment]
Did this happened when you were typing in Google's search bar or when you were typing in Qupzilla's search widget (the one that pops in when you type ctrl+f)?

Qupzilla is not supposed to forward keys events consumed by the page to plugins. This is the case for Google's search bar. I can't look this right now but I'll take a look when I leave work.

Thanks for reporting

**Comment by Sandmonster** [comment]
In Arch's repos only qt 5.9.1 version, so I compiled with workaround m_rwhvqt you posted here: [https://github.com/QupZilla/qupzilla/issues/2369](QupZilla/qupzilla/issues/2369). That's must be the reason

**Comment by Sandmonster** [comment]
And to answer a question it's in Google's search bar

**Comment by joseriosneto** [comment]
> In Arch's repos only qt 5.9.1 version, so I compiled with workaround m_rwhvqt you posted here: https://github.com/QupZilla/qupzilla/issues/2369. That's must be the reason

That's why :)

As you can see in the other issue, qtwebengine5.9 and 5.9.1 have a bug. Roughly they are supposed to send back to QupZilla unconsumed key press events but they don't. For consumed key press events as typing in Google's search bar it's fine to don't return them so QupZilla doesn't forward them to plugins and avoids problems like the one you mentioned. For unconsumed on the other hand it shall return so QupZilla can give plugins a chance to handle them. 

That hack was making QupZilla (which gets the event in first hand) send all key press events to plugins regardless if the page would consume them. That makes the browser indeed useless (imagine yourself writing an import document in gdoc with this bug :).

I'm afraid there's no easy solution other than using a qtwebengine version has this bug fixed (5.8* or >= 5.9.2). The plugin doesn't even receive the events so it would be really hard to work around this without changing QupZilla's code. I'll add a comment in the other issue for that hack. I'll also add back a note in README to avoid future issues on this.
